name: "Panel Alarm Intelbras Hub - MQTT"
version: "0.3.10"
slug: "intelbras_bridge"
description: "Full-featured bridge for Intelbras alarm panels (AMT-8000 and similar) via MQTT."
url: "https://github.com/pepito2k/addons-alarma-intelbras"
arch:
  - aarch64
  - amd64
#icon: "icon.png"
hassio_api: true
homeassistant_api: true
startup: "application"
boot: "auto"
init: false
host_network: true
services:
  - "mqtt:want"
ports:
  "9009/tcp": null
ports_description:
  "9009/tcp": "Port for the alarm panel to send events to this Add-on"
options:
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  alarm_ip: ""
  alarm_port: 9009
  alarm_password: ""
  alarm_protocol: "isecnet"
  password_length: 6
  polling_interval_minutes: 5
  zone_count: 8
  #zone_names: []
  #zone_types: []
schema:
  mqtt_broker: str
  mqtt_port: port
  mqtt_user: str
  mqtt_password: password
  alarm_ip: str
  alarm_port: port
  alarm_password: password
  alarm_protocol: list(isecnet|legacy)
  password_length: int(4,6)
  polling_interval_minutes: int(0,1440)
  zone_count: int(1,64)
  #zone_names: [str]
  #zone_types: [str]
