name: "Intelbras AMT 4010/8000 Bridge - MQTT"
version: "0.4.6"
slug: "intelbras_bridge"
description: "MQTT bridge for Intelbras AMT 4010 (ISECNet) and AMT-8000 (amt8000) alarm panels."
url: "https://github.com/pepito2k/addons-alarma-intelbras"
arch:
  - aarch64
  - amd64
#icon: "icon.png"
hassio_api: true
homeassistant_api: true
startup: "application"
boot: "auto"
init: false
host_network: true
services:
  - "mqtt:want"
ports:
  "9009/tcp": null
ports_description:
  "9009/tcp": "Port for the alarm panel to send events to this Add-on"
options:
  mqtt_broker: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  alarm_ip: ""
  alarm_port: 9009
  alarm_password: ""
  alarm_protocol: "isecnet"
  password_length: 6
  polling_interval_minutes: 5
  zone_range: "1-8"
  zone_names: "{}"
  zone_count: 8
  #zone_names: []
  #zone_types: []
schema:
  mqtt_broker: str
  mqtt_port: port
  mqtt_user: str
  mqtt_password: password
  alarm_ip: str
  alarm_port: port
  alarm_password: password
  alarm_protocol: list(isecnet|amt8000)
  password_length: int(4,6)
  polling_interval_minutes: int(1,1440)
  zone_range: str
  zone_names: str
  zone_count: int(0,64)
  #zone_names: [str]
  #zone_types: [str]
